# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Speedy
tagline:          190 IOS Group
url:              http://kkolli.github.io
paginate:         1
baseurl:          /MathGame/
author:
  name:           Speedy Math
  url:            http://kkolli.github.io/
  email:          jychou@ucsd.edu

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
